module.exports = {
  // official documents
  FEDERAL_TAX_ID: 'FEDERAL_TAX_ID',
  GENERAL_REGISTRY: 'GENERAL_REGISTRY',
  PASSPORT: 'PASSPORT',
  REGIONAL_MEDICAL_COUNCIL: 'REGIONAL_MEDICAL_COUNCIL',
  REGIONAL_NURSING_COUNCIL: 'REGIONAL_NURSING_COUNCIL',
}
